# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_area', models.CharField(choices=[('CH', '中国大陆'), ('TW', '台湾'), ('GA', '港澳'), ('HW', '海外其他')], default='CH', max_length=10)),
                ('address_city', models.CharField(max_length=20)),
                ('address_class', models.CharField(max_length=20)),
                ('address_full', models.CharField(max_length=100)),
                ('address_zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Luser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_qq', models.CharField(max_length=30)),
                ('user_weixin', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_eval', models.TextField()),
                ('user_address', models.ManyToManyField(to='orders.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('ST', '孙老板'), ('FW', '微信'), ('FT', '淘宝'), ('OT', '其他')], default='ST', max_length=10)),
                ('order_money', models.FloatField()),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('JL', '建立订单'), ('FH', '订单发货'), ('BH', '部分发货'), ('CJ', '已成交'), ('QX', '订单取消'), ('BX', '部分取消')], max_length=10)),
                ('order_eval', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('product_cate', models.CharField(max_length=20)),
                ('product_brand', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.TextField()),
                ('product_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_type', models.CharField(choices=[('TTO', '天天快递'), ('SFO', '顺丰快递'), ('ZTO', '中通快递'), ('YTO', '圆通快递'), ('STO', '申通快递'), ('EMS', '邮政EMS'), ('YDO', '韵达快递'), ('HTO', '汇通快递'), ('ZJS', '宅急送'), ('BSO', '百世汇通'), ('YSO', '优速快递'), ('DBO', '德邦物流'), ('QTO', '其他')], default='ZTO', max_length=16)),
                ('track_num', models.CharField(max_length=20)),
                ('track_price', models.FloatField()),
                ('track_printtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Track'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Luser'),
        ),
    ]
