# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170723_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='luser',
            name='user_weibo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='luser',
            name='user_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='luser',
            name='user_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='luser',
            name='user_qq',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='luser',
            name='user_taobao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='luser',
            name='user_weixin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
