# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170729_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_zip',
            new_name='address_province',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_area',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_city',
            field=models.CharField(max_length=10),
        ),
    ]
