# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_luser_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='luser',
            name='user_address',
            field=models.ManyToManyField(blank=True, to='orders.Address'),
        ),
    ]
